-- AlterTable
ALTER TABLE "Comment_GROUP" ALTER COLUMN "mediaUrl" DROP NOT NULL,
ALTER COLUMN "content" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Comment_PAGE" ALTER COLUMN "mediaUrl" DROP NOT NULL,
ALTER COLUMN "content" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Comment_PAGESHARE" ALTER COLUMN "mediaUrl" DROP NOT NULL,
ALTER COLUMN "content" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Comment_PAGESHARE_TOGROUP" ALTER COLUMN "mediaUrl" DROP NOT NULL,
ALTER COLUMN "content" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Comment_USER" ALTER COLUMN "mediaUrl" DROP NOT NULL,
ALTER COLUMN "content" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Comment_USERSHARE" ALTER COLUMN "mediaUrl" DROP NOT NULL,
ALTER COLUMN "content" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Comment_USERSHARE_TOGROUP" ALTER COLUMN "mediaUrl" DROP NOT NULL,
ALTER COLUMN "content" DROP NOT NULL;
